from django.urls import include, path

from . import views


urlpatterns = [
    path('test', views.test),
    path('addRegistrationID/<int:userID>/<str:token>/<str:ID>', views.addRegistrationID),
    path('verifyRecipt/<int:userID>/<str:token>', views.verifyReceipt),
    path('addNewZipcode/<int:zip>/<str:token>', views.addNewZipcode),
    path('openApp', views.openApp),
    path('canUserChangePassword/<str:login>', views.canUserChangePsw),
    path('resetPassword/<int:userID>', views.resetPsw),
    path('sendResetPasswordEmail/<str:login>', views.sendResetPswEmail),
    path('isUserVerified/<int:userID>/<str:token>', views.isUserVerified),
    path('sendVerificationEmail/<int:userID>/<str:token>', views.sendVerifEmail),
    path('verifyUser/<int:userID>/<str:token>', views.verifyUser),
    path('updateUserZip/<int:userID>/<int:zip>/<str:token>', views.updateUserZip),
    path('addSubmission/<str:supply>/<str:token>', views.addSubmission),
    path('deleteSKURegionNotification/<int:userID>/<int:productID>/<int:radius>/<str:city>/<str:date>/<str:token>', views.deleteSKURegionNotification),
    path('deleteSKUStoreNotification/<int:userID>/<int:productID>/<int:storeID>/<str:date>/<str:token>', views.deleteSKUStoreNotification),
    path('deleteSupplyRegionNotification/<int:userID>/<str:supply>/<int:radius>/<str:city>/<str:date>/<str:token>', views.deleteSupplyRegionNotification),
    path('getStoreNotifications/<int:userID>/<str:token>', views.getStoreNotifications),
    path('getAreaNotifications/<int:userID>/<str:token>', views.getAreaNotifications),
    path('changePassword/<str:login>/<str:salt>/<str:newPsw>/<str:type>', views.changePassword),
    path('updateUserProfile/<int:userID>/<str:fName>/<str:usrname>/<str:email>/<str:token>', views.updateUserProfile),
    path('addSupplyRegionNotification/<int:userID>/<str:supply>/<int:radius><str:metric>/<str:city>/<latitude>/<longitude>/<str:date>/<str:token>', views.addSupplyRegionNotification),
    path('addSKURegionNotification/<int:userID>/<int:sku>/<int:radius><str:metric>/<str:city>/<latitude>/<longitude>/<str:date>/<str:token>', views.addSKURegionNotification),
    path('addSKUStoreNotification/<int:userID>/<int:sku>/<int:storeID>/<str:date>/<str:token>', views.addSKUStoreNotification),
    path('getTotalQuantityOf/<str:supply>/<int:storeID>/<str:token>', views.getTotalQuantity),
    path('getUserInfo/<str:login>', views.getUserInfo),
    path('getSalt', views.getSalt),
    path('loginUser/<str:login>/<str:psw>/<lat>/<lon>/<str:token>', views.loginUser),
    path('registerUser/<str:fname>/<str:email>/<str:username>/<str:salt>/<str:psw>/<int:zip>', views.registerUser),
    path('getStoreWithSupply/<str:supply>/<int:storeID>/<str:token>', views.getStoreWithSupply),
    path('getStoresWithSupply_Notif/<str:supply>/<int:radius><str:metric>/<latitude>/<longitude>/<str:token>', views.getStoresWithSupply_Notif),
    path('getStoreWithSKU/<int:storeID>/<int:sku>/<str:token>', views.getStoreWithSKU),
    path('getStoresWithSKU/<int:sku>/<int:radius><str:metric>/<latitude>/<longitude>/<str:token>', views.getStoresWithSKU),
    path('getNearbyStores/<int:sku>/<int:radius><str:metric>/<latitude>/<longitude>/<int:storeID>/<str:token>', views.getNearbyStores),
    path('getProductsInStore/<str:supply>/<int:storeID>/<str:token>', views.getProductsInStore),
    path('getStoresWithSupply/<str:supply>/<int:radius><str:metric>/<latitude>/<longitude>/<str:token>', views.getStoresWithSupply),
    path('getSupplyOptions/<str:token>', views.getSupplyOptions),
    path('', views.main),
]